version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    restart: always
    volumes:
      - ./api:/app

networks:
    code-network:
        driver: bridge